# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyExchange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyExchange

  pod 'AlamofireObjectMapper'
  pod 'Alamofire', '~> 4.4'
  pod 'ObjectMapper'
  pod 'iOSDropDown'
   
  target 'CurrencyExchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyExchangeUITests' do
    # Pods for testing
  end

end
